module SpriteHelper
  # 16x16 pixel art, drawn as text so it stays editable by hand. Rendered to
  # inline SVG with horizontal runs merged into single rects, which keeps each
  # sprite around a kilobyte and costs zero network requests.
  SPRITES = {
    "cursor" => %w[
      .XX.............
      .XXX............
      .XXXX...........
      .XXXXX..........
      .XXXXXX.........
      .XXXXXXX........
      .XXXXXXXX.......
      .XXXXXXXXX......
      .XXXXXXXXXX.....
      .XXXXXXX........
      .XX.XXXX........
      .X..XXXX........
      ......XXXX......
      ......XXXX......
      .......XX.......
      ................
    ],
    "floppy" => %w[
      ................
      .XXXXXXXXXXXXX..
      .X...........X..
      .X..XXXXXXX..X..
      .X..X.....X..X..
      .X..X.....X..X..
      .X..XXXXXXX..X..
      .X...........X..
      .X...........X..
      .X.XXXXXXXXX.X..
      .X.X.......X.X..
      .X.X.......X.X..
      .X.X.......X.X..
      .XXXXXXXXXXXXX..
      ................
      ................
    ],
    "dialog" => %w[
      ................
      .XXXXXXXXXXXXXX.
      .X............X.
      .XXXXXXXXXXXXXX.
      .X............X.
      .X..XXXXXXXX..X.
      .X............X.
      .X..XXXXXXXX..X.
      .X............X.
      .X..XXXX......X.
      .X............X.
      .X......XXXXX.X.
      .X............X.
      .XXXXXXXXXXXXXX.
      ................
      ................
    ],
    "key" => %w[
      ................
      ....XXXXXX......
      ...XX....XX.....
      ...X......X.....
      ...X......X.....
      ...XX....XX.....
      ....XXXXXX......
      ......XX........
      ......XX........
      ......XXXX......
      ......XX........
      ......XXX.......
      ......XX........
      ......XXX.......
      ................
      ................
    ],
    "clock" => %w[
      ................
      .....XXXXXX.....
      ...XX......XX...
      ..X..........X..
      ..X....XX....X..
      .X.....XX.....X.
      .X.....XX.....X.
      .X.....XXXXX..X.
      .X............X.
      ..X..........X..
      ..X..........X..
      ...XX......XX...
      .....XXXXXX.....
      ................
      ................
      ................
    ],
    "brick" => %w[
      ................
      .XXXXXXXXXXXXXX.
      .X....X....X..X.
      .XXXXXXXXXXXXXX.
      .X..X....X....X.
      .XXXXXXXXXXXXXX.
      .X....X....X..X.
      .XXXXXXXXXXXXXX.
      .X..X....X....X.
      .XXXXXXXXXXXXXX.
      .X....X....X..X.
      .XXXXXXXXXXXXXX.
      ................
      ................
      ................
      ................
    ],
  }.freeze

  def sprite(name, size: 40)
    rows = SPRITES.fetch(name.to_s, SPRITES.fetch("brick"))
    rects = rows.each_with_index.flat_map { |row, y| runs(row).map { |x, w| %(<rect x="#{x}" y="#{y}" width="#{w}" height="1"/>) } }
    raw <<~SVG.squish
      <svg class="sprite" viewBox="0 0 16 16" width="#{size}" height="#{size}"
           aria-hidden="true" focusable="false" shape-rendering="crispEdges"
           fill="currentColor">#{rects.join}</svg>
    SVG
  end

  private
    # Collapses each row of pixels into [start_x, width] runs.
    def runs(row)
      row.chars.each_with_index.chunk_while { |(a, i), (b, j)| a == b && j == i + 1 }
        .select { |chunk| chunk.first.first == "X" }
        .map { |chunk| [chunk.first.last, chunk.length] }
    end
end
